### ISSUE TITLE
Can't build Nice Vibrations Asset

### ISSUE THREAD

**Issue by shefich** [Lofelt/NiceVibrations#23]
# Bug report

## Checklist
- [ ] I'm using the latest release
- [ ] I've searched for existing issue

## Goals
I wan to build Nice Vibrations Asset.

## Steps to Reproduce
Download the whole repository and run "sh build.sh" inside the main folder.

## Expected behavior
Once its finished,a nice-vibrations-asset folder is created which contains the NiceVibrations asset.

## Observed behavior
I can see such errors:
"~/Desktop/NiceVibrations-main
$ sh build.sh
➡️ Cleaning Nice Vibrations asset artifacts
➡️ Cleaning copied build artifacts
➡️ Building for iOS
rm: cannot remove 'derived_data': No such file or directory
===========================================
Building archive for iOS Simulator
===========================================
build-xcframework.sh: line 20: xcodebuild: command not found
❌ Failed to build archive for iOS Simulator
❌ Building iOS XCFramework failed
"

**Comment by shefich** [comment]
Also it would be better to have latest release folder with the latest *.unitypackage file inside.

**Comment by shefich** [comment]
Ok, I removed build for the iOS and now have another error, probably it says that I don't have Lofelt Studio SDK installed.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':LofeltHaptics'.
> Failed to notify project evaluation listener.
   > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\User\Desktop\NiceVibrations\NiceVibrations-main\interfaces\android\LofeltHaptics\local.properties'.
   > Task with name 'cargoBuild' not found in project ':LofeltHaptics'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
❌ Failed to clean the build
❌ Building Android library failed

**Comment by shefich** [comment]
Please, just give me a link to the Unity package/asset.

**Comment by shefich** [comment]
Ok nevermind, found this: https://github.com/Lofelt/NiceVibrations/releases/tag/sdk-1.3.4-nicevibrations-4.1.2

**Comment by BenTailors** [comment]
Hey shefich, Glad to hear you could get this unblocked yourself! We're closing this issue. Best,
