### ISSUE TITLE
 Showing Recent Messages Framework 'LofeltHaptics' not found | Xcode build error for Unity mobile game

### ISSUE THREAD

**Issue by calindeva** [Lofelt/NiceVibrations#34]
# Bug report

## Checklist
- [* ] I'm using the latest release
- [* ] I've searched for existing issue

## Environment
We are using Unity 2021.3.27f1 along with Feel 3.13.0, building the game for Android and iOS

## Goals
We wanted to integrate haptic feedbacks on our UI buttons and build the game successfully for both Android and iOS

## Steps to Reproduce
Integrate Feel into the game, place the functions for the haptic feedbacks on UI buttons and build the game for iOS then try to build it into xcode on a MAC machine

## Expected behavior
It should build successfully in xcode then be able to upload it to the app store, on android it works without any problem.

## Observed behavior
After it was exported from unity and tried to be built in xcode it will throw this error and the build stop:

**Framework 'LofeltHaptics' not found
Linker command failed with exit code 1 (use -v to see invocation)
ld: warning: ignoring duplicate libraries: '-lc++'
ld: framework 'LofeltHaptics' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

## Code Samples & Details
<Please provide a code sample if necessary, as well as any additional details, to help us track down the issue.>

**Comment by UgurEmre06** [comment]
Paste your \Assets\Plugins\Feel\NiceVibrations\Plugins\iOS\LofeltHaptics.frame file into > Pods\NiceVibrations (create NiceVibrations folder) in your xcode build output. Then link this file as a framework via Xcode

**Comment by SerdarEvry** [comment]
> Paste your \Assets\Plugins\Feel\NiceVibrations\Plugins\iOS\LofeltHaptics.frame file into > Pods\NiceVibrations (create NiceVibrations folder) in your xcode build output. Then link this file as a framework via Xcode

That solved the problem for me a year later! Thanks.
